# This is a basic workflow to help you get started with Actions

name: Metrics

# Controls when the workflow will run
on:
  schedule: [{cron: "0 0 * * *"}]
  
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
